<!-- 入库管理：采购入库+退货入库，选供应商添加商品明细 -->
<template>
  <div class="ct"><el-card class="sc"><el-form :inline="true" :model="s"><el-form-item label="单号"><el-input v-model="s.inNo" placeholder="入库单号" clearable @keyup.enter="load"/></el-form-item><el-form-item label="类型"><el-select v-model="s.inType" placeholder="全部" clearable style="width:130px"><el-option label="采购入库" value="purchase"/><el-option label="退货入库" value="return"/></el-select></el-form-item><el-form-item label="状态"><el-select v-model="s.status" placeholder="全部" clearable style="width:110px"><el-option label="草稿" value="draft"/><el-option label="已提交" value="pending"/><el-option label="已审核" value="approved"/></el-select></el-form-item><el-form-item><el-button type="primary" @click="load"><el-icon><Search /></el-icon></el-button><el-button @click="s.inNo='';s.inType='';s.status='';s.pageNum=1;load()"><el-icon><Refresh /></el-icon></el-button></el-form-item></el-form></el-card>
    <el-card class="tc"><div class="tb"><el-button type="primary" @click="handleAdd"><el-icon><Plus /></el-icon> 新增入库单</el-button></div>
      <el-table :data="list" border stripe v-loading="ld"><el-table-column prop="id" label="ID" width="60" align="center"/><el-table-column prop="inNo" label="入库单号" width="170"/><el-table-column label="类型" width="100" align="center"><template #default="{row}">{{row.inType==='purchase'?'采购入库':'退货入库'}}</template></el-table-column><el-table-column label="操作人" width="100" align="center"><template #default="{row}">{{ userMap[row.operator] || '-' }}</template></el-table-column><el-table-column prop="totalAmount" label="总金额" width="120" align="right"/><el-table-column label="状态" width="90" align="center"><template #default="{row}"><el-tag v-if="row.status==='draft'" type="info">草稿</el-tag><el-tag v-else-if="row.status==='pending'" type="warning">待审核</el-tag><el-tag v-else-if="row.status==='approved'" type="success">已审核</el-tag></template></el-table-column><el-table-column prop="remark" label="备注" min-width="160" show-overflow-tooltip/><el-table-column prop="createTime" label="时间" width="160" align="center"><template #default="{row}">{{row.createTime?row.createTime.substring(0,16):'-'}}</template></el-table-column>
        <el-table-column label="操作" width="220" align="center"><template #default="{row}"><el-button size="small" @click="view(row)"><el-icon><View /></el-icon></el-button><el-button v-if="row.status==='draft'" size="small" type="warning" @click="edit(row)"><el-icon><Edit /></el-icon></el-button><el-button v-if="row.status==='draft'" size="small" type="success" @click="submit(row)">提交</el-button><el-button v-if="row.status==='draft'" size="small" type="danger" @click="del(row)"><el-icon><Delete /></el-icon></el-button></template></el-table-column></el-table>
      <div class="pg"><el-pagination v-model:current-page="s.pageNum" v-model:page-size="s.pageSize" :page-sizes="[10,20,50]" :total="total" layout="total,sizes,prev,pager,next,jumper" @size-change="load" @current-change="load"/></div>
    </el-card>
    <el-dialog v-model="dv" :title="isE?'编辑入库单':'新增入库单'" width="850px" @closed="rf"><el-form :model="f" label-width="80px"><el-row :gutter="16"><el-col :span="8"><el-form-item label="入库类型"><el-select v-model="f.inType" style="width:100%"><el-option label="采购入库" value="purchase"/><el-option label="退货入库" value="return"/></el-select></el-form-item></el-col><el-col :span="8"><el-form-item label="供应商"><el-select v-model="f.supplierId" filterable placeholder="搜索供应商" style="width:100%"><el-option v-for="s2 in suppliers" :key="s2.id" :label="s2.supplierName" :value="s2.id"/></el-select></el-form-item></el-col><el-col :span="8"><el-form-item label="仓库"><el-select v-model="f.warehouseId" placeholder="选择仓库" style="width:100%" @change="loadLoc"><el-option v-for="w in whs" :key="w.id" :label="w.warehouseName" :value="w.id"/></el-select></el-form-item></el-col></el-row><el-form-item label="备注"><el-input v-model="f.remark" placeholder="选填" maxlength="200"/></el-form-item>
      <el-divider>商品明细</el-divider>
      <el-table :data="f.details" border size="small"><el-table-column label="商品" min-width="200"><template #default="{row}"><el-select v-model="row.productId" filterable placeholder="搜索商品" style="width:100%" @change="v=>onProduct(row,v)"><el-option v-for="p in prods" :key="p.id" :label="p.productName+' ('+p.productCode+')'" :value="p.id"/></el-select></template></el-table-column><el-table-column label="库位" width="160"><template #default="{row}"><el-select v-model="row.locationId" placeholder="选择库位" style="width:100%"><el-option v-for="l in locs" :key="l.id" :label="l.locationName" :value="l.id"/></el-select></template></el-table-column><el-table-column label="数量" width="100" align="center"><template #default="{row}"><el-input-number v-model="row.quantity" :min="1" size="small" controls-position="right" @change="calc(row)"/></template></el-table-column><el-table-column label="单价" width="130" align="right"><template #default="{row}"><el-input-number v-model="row.unitPrice" :min="0" :precision="2" size="small" controls-position="right" @change="calc(row)"/></template></el-table-column><el-table-column label="金额" width="120" align="right"><template #default="{row}">{{row.amount||0}}</template></el-table-column><el-table-column width="60" align="center"><template #default="{$index}"><el-button size="small" type="danger" @click="f.details.splice($index,1)"><el-icon><Delete /></el-icon></el-button></template></el-table-column></el-table>
      <div class="df"><el-button size="small" @click="addDetail"><el-icon><Plus /></el-icon> 添加商品</el-button><span class="tt">合计：<strong>¥{{totalAmount}}</strong></span></div></el-form>
      <template #footer><el-button @click="dv=false">取消</el-button><el-button @click="save('draft')">保存草稿</el-button><el-button type="primary" :loading="sb" @click="save('pending')">保存并提交</el-button></template></el-dialog>
  </div>
</template>
<script setup>
import {ref,reactive,computed,onMounted} from 'vue';import {ElMessage,ElMessageBox} from 'element-plus'
import {Search,Refresh,Plus,Edit,Delete,View} from '@element-plus/icons-vue'
import {getStockInPage,getStockInById,createStockIn,updateStockIn,deleteStockIn,updateStockInStatus,getSuppliers,getWarehouses,getLocations,searchProducts,getUserPage} from '../../../api/index.js'
import {confirmDelete} from '../../../utils/confirm.js'
const s=reactive({pageNum:1,pageSize:10,inNo:'',inType:'',status:''}),list=ref([]),total=ref(0),ld=ref(false)
const load=async()=>{ld.value=true;try{const r=await getStockInPage(s);if(r.code===200){list.value=r.data.list;total.value=r.data.total}}finally{ld.value=false}}
const dv=ref(false),isE=ref(false),eId=ref(null),sb=ref(false),suppliers=ref([]),whs=ref([]),prods=ref([]),locs=ref([]),userMap=ref({})
const f=reactive({inType:'purchase',supplierId:null,warehouseId:null,remark:'',details:[]})
const totalAmount=computed(()=>f.details.reduce((s2,d)=>s2+(Number(d.amount)||0),0).toFixed(2))
const loadSup=async()=>{const r=await getSuppliers();if(r.code===200)suppliers.value=r.data}
const loadUsers=async()=>{const r=await getUserPage({pageNum:1,pageSize:100});if(r.code===200){(r.data.list||[]).forEach(u=>userMap.value[u.id]=u.realName||u.username)}}
const loadWhs=async()=>{const r=await getWarehouses();if(r.code===200)whs.value=r.data}
const loadProds=async(kw)=>{const r=await searchProducts(kw||'');if(r.code===200)prods.value=r.data}
const loadLoc=async(wid=f.warehouseId)=>{if(!wid)return;const r=await getLocations(wid);if(r.code===200)locs.value=r.data}
const addDetail=()=>f.details.push({productId:null,locationId:null,quantity:1,unitPrice:0,amount:0})
const calc=(row)=>{row.amount=(Number(row.quantity)||0)*(Number(row.unitPrice)||0)}
const onProduct=(row,pid)=>{const p=prods.value.find(x=>x.id===pid);if(p)row.unitPrice=p.costPrice||0;calc(row)}
const handleAdd=async()=>{isE.value=false;eId.value=null;await loadSup();await loadWhs();await loadProds();await loadUsers();dv.value=true}
const edit=async(row)=>{isE.value=true;eId.value=row.id;await loadSup();await loadWhs();await loadProds();const r=await getStockInPage(s);/*直接用详情*/ const r2=await getStockInById(row.id);if(r2&&r2.code===200){const o=r2.data.order;f.inType=o.inType;f.supplierId=o.supplierId;f.warehouseId=o.warehouseId;f.remark=o.remark||'';await loadLoc(o.warehouseId);f.details=r2.data.details.map(d=>({productId:d.productId,locationId:d.locationId,quantity:Number(d.quantity)||1,unitPrice:Number(d.unitPrice)||0,amount:Number(d.amount)||0}))}dv.value=true}
const rf=()=>{f.inType='purchase';f.supplierId=null;f.warehouseId=null;f.remark='';f.details=[];eId.value=null}
const save=async(status)=>{if(!f.supplierId||!f.warehouseId){ElMessage.warning('请选择供应商和仓库');return}if(f.details.length===0){ElMessage.warning('请添加商品明细');return}sb.value=true;try{const d={inType:f.inType,supplierId:f.supplierId,warehouseId:f.warehouseId,remark:f.remark,status,details:f.details};const r=isE.value?await updateStockIn({...d,id:eId.value}):await createStockIn(d);if(r.code===200){ElMessage.success(r.msg);dv.value=false;load()}else ElMessage.error(r.msg)}finally{sb.value=false}}
const submit=async(row)=>{try{await ElMessageBox.confirm('确认提交该入库单？','提示',{type:'warning'});await updateStockInStatus(row.id,'pending');ElMessage.success('已提交');load()}catch(e){}}
const del=async(row)=>{try{await confirmDelete('确定删除「'+row.inNo+'」吗？');const r=await deleteStockIn(row.id);if(r.code===200){ElMessage.success('已删除');load()}else ElMessage.error(r.msg)}catch(e){}}
const view=async(row)=>{const r=await getStockInById(row.id);if(r&&r.code===200)ElMessageBox.alert('单号：'+r.data.order.inNo+'\n类型：'+(r.data.order.inType==='purchase'?'采购入库':'退货入库')+'\n金额：¥'+r.data.order.totalAmount+'\n备注：'+(r.data.order.remark||'无'),'入库单详情',{confirmButtonText:'关闭'})}
onMounted(()=>{load();loadUsers()})
</script>
<style scoped>.ct{padding:0}.sc,.tc{margin-bottom:16px}.tb{margin-bottom:16px}.pg{margin-top:16px;display:flex;justify-content:flex-end}.df{display:flex;justify-content:space-between;align-items:center;margin-top:12px}.tt{font-size:16px}.tt strong{color:#e74c3c}</style>
